security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\User\Domain\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(?:_(profiler|wdt))
      security: false

    # tylko logowanie po JSON
    login:
      pattern: ^/api/auth/login$
      stateless: true
      provider: app_user_provider
      json_login:
        check_path: /api/auth/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    # reszta API – wymaga JWT
    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~

  access_control:
    - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/admin, roles: ROLE_ADMIN }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/user_word_progress, roles: IS_AUTHENTICATED_FULLY }
